name: Static type check
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ./Gemfile
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: mrubyc-test
      run: CFLAGS=-DMAX_SYMBOLS_COUNT=1000 MRUBYCFILE=test/Mrubycfile bundle exec mrubyc-test
      working-directory: .

